ospathbasename_aspect: &default_aspect
  warmups: 10
  internal_loop: 100
  function_name: "iast_ospathbasename_aspect"
  iast_enabled: true

ospathbasename_noaspect:
  <<: *default_aspect
  function_name: "ospathbasename_noaspect"
  iast_enabled: false

# TODO: Big regression flakiness (APPSEC-57818)
#ospathdirname_aspect: &ospathdirname_aspect
#  warmups: 1
#  function_name: "iast_ospathdirname_aspect"
#
#ospathdirname_noaspect:
#  <<: *ospathdirname_aspect
#  function_name: "ospathdirname_noaspect"

ospathjoin_aspect:
  <<: *default_aspect
  function_name: "iast_ospathjoin_aspect"

ospathjoin_noaspect:
  <<: *default_aspect
  function_name: "ospathjoin_noaspect"
  iast_enabled: false

ospathnormcase_aspect:
  <<: *default_aspect
  function_name: "iast_ospathnormcase_aspect"

ospathnormcase_noaspect:
  <<: *default_aspect
  function_name: "ospathnormcase_noaspect"
  iast_enabled: false

ospathsplit_aspect:
  <<: *default_aspect
  function_name: "iast_ospathsplit_aspect"

ospathsplit_noaspect:
  <<: *default_aspect
  function_name: "ospathsplit_noaspect"
  iast_enabled: false

ospathsplitdrive_aspect:
  <<: *default_aspect
  function_name: "iast_ospathsplitdrive_aspect"

ospathsplitdrive_noaspect:
  <<: *default_aspect
  function_name: "ospathsplitdrive_noaspect"
  iast_enabled: false

ospathsplitext_aspect:
  <<: *default_aspect
  function_name: "iast_ospathsplitext_aspect"

ospathsplitext_noaspect:
  <<: *default_aspect
  function_name: "ospathsplitext_noaspect"
  iast_enabled: false