rsplit_aspect: &default_aspect
  warmups: 10
  internal_loop: 100
  function_name: "iast_rsplit_aspect"
  iast_enabled: true

rsplit_noaspect:
  <<: *default_aspect
  function_name: "rsplit_noaspect"
  iast_enabled: false

split_aspect:
  <<: *default_aspect
  function_name: "iast_split_aspect"

split_noaspect:
  <<: *default_aspect
  function_name: "split_noaspect"
  iast_enabled: false

splitlines_aspect:
  <<: *default_aspect
  function_name: "iast_splitlines_aspect"

splitlines_noaspect:
  <<: *default_aspect
  function_name: "splitlines_noaspect"
  iast_enabled: false