baseline: &baseline
  tracer_enabled: false
  profiler_enabled: false
  appsec_enabled: false
  iast_enabled: false
  post_request: false
  telemetry_metrics_enabled: false
tracer:
  <<: *baseline
  tracer_enabled: true
profiler:
  <<: *baseline
  profiler_enabled: true
iast-get:
  <<: *baseline
  iast_enabled: true
appsec-get: &appsec
  <<: *baseline
  tracer_enabled: true
  appsec_enabled: true
appsec-post:
  <<: *appsec
  post_request: true
appsec-telemetry:
  <<: *appsec
  telemetry_metrics_enabled: true
tracer-and-profiler:
  <<: *baseline
  tracer_enabled: true
  profiler_enabled: true
tracer-and-profiler-and-appsec:
  <<: *baseline
  tracer_enabled: true
  profiler_enabled: true
  appsec_enabled: true
  post_request: true
