add_aspect: &default_aspect
  warmups: 5
  internal_loop: 100
  function_name: "iast_add_aspect"
  iast_enabled: true
  default_function_type: "str"

add_noaspect:
  <<: *default_aspect
  function_name: "add_noaspect"
  iast_enabled: false

add_inplace_aspect:
  <<: *default_aspect
  function_name: "iast_add_inplace_aspect"

add_inplace_noaspect:
  <<: *default_aspect
  function_name: "add_inplace_noaspect"
  iast_enabled: false

bytearray_aspect: 
  <<: *default_aspect
  function_name: "iast_bytearray_aspect"
  default_function_type: "bytes"

bytearray_noaspect:
  <<: *default_aspect
  function_name: "bytearray_noaspect"
  iast_enabled: false
  default_function_type: "bytes"

bytearray_extend_aspect:
  <<: *default_aspect
  function_name: "iast_bytearray_extend_aspect"
  default_function_type: "bytearray"

bytearray_extend_noaspect:
  <<: *default_aspect
  function_name: "bytearray_extend_noaspect"
  iast_enabled: false
  default_function_type: "bytearray"

bytes_aspect:
  <<: *default_aspect
  function_name: "iast_bytes_aspect"

bytes_noaspect:
  <<: *default_aspect
  function_name: "bytes_noaspect"
  iast_enabled: false

bytesio_aspect:
  <<: *default_aspect
  function_name: "iast_bytesio_aspect"
  default_function_type: "bytes"

bytesio_noaspect:
  <<: *default_aspect
  function_name: "bytesio_noaspect"
  iast_enabled: false
  default_function_type: "bytes"

capitalize_aspect:
  <<: *default_aspect
  function_name: "iast_capitalize_aspect"

capitalize_noaspect:
  <<: *default_aspect
  function_name: "capitalize_noaspect"
  iast_enabled: false

casefold_aspect:
  <<: *default_aspect
  function_name: "iast_casefold_aspect"

casefold_noaspect:
  <<: *default_aspect
  function_name: "casefold_noaspect"
  iast_enabled: false

decode_aspect:
  <<: *default_aspect
  function_name: "iast_decode_aspect"
  default_function_type: "bytes"

decode_noaspect:
  <<: *default_aspect
  function_name: "decode_noaspect"
  iast_enabled: false
  default_function_type: "bytes"

encode_aspect:
  <<: *default_aspect
  function_name: "iast_encode_aspect"

encode_noaspect:
  <<: *default_aspect
  function_name: "encode_noaspect"
  iast_enabled: false

format_aspect:
  <<: *default_aspect
  function_name: "iast_format_aspect"

format_noaspect:
  <<: *default_aspect
  function_name: "format_noaspect"
  iast_enabled: false

format_map_aspect:
  <<: *default_aspect
  function_name: "iast_format_map_aspect"

format_map_noaspect:
  <<: *default_aspect
  function_name: "format_map_noaspect"
  iast_enabled: false

index_aspect:
  <<: *default_aspect
  function_name: "iast_index_aspect"

index_noaspect:
  <<: *default_aspect
  function_name: "index_noaspect"
  iast_enabled: false

join_aspect:
  <<: *default_aspect
  function_name: "iast_join_aspect"

join_noaspect:
  <<: *default_aspect
  function_name: "join_noaspect"
  iast_enabled: false

strip_aspect:
  <<: *default_aspect
  function_name: "iast_strip_aspect"

strip_noaspect:
  <<: *default_aspect
  function_name: "strip_noaspect"
  iast_enabled: false

rstrip_aspect:
  <<: *default_aspect
  function_name: "iast_rstrip_aspect"

rstrip_noaspect:
  <<: *default_aspect
  function_name: "rstrip_noaspect"
  iast_enabled: false

lstrip_aspect:
  <<: *default_aspect
  function_name: "iast_lstrip_aspect"

lstrip_noaspect:
  <<: *default_aspect
  function_name: "lstrip_noaspect"
  iast_enabled: false

lower_aspect:
  <<: *default_aspect
  function_name: "iast_lower_aspect"

lower_noaspect:
  <<: *default_aspect
  function_name: "lower_noaspect"
  iast_enabled: false

ljust_aspect:
  <<: *default_aspect
  function_name: "iast_ljust_aspect"

ljust_noaspect:
  <<: *default_aspect
  function_name: "ljust_noaspect"
  iast_enabled: false

modulo_aspect:
  <<: *default_aspect
  function_name: "iast_modulo_aspect"

modulo_aspect_for_bytes:
  <<: *default_aspect
  function_name: "iast_modulo_aspect_for_bytes"
  default_function_type: "bytes"

modulo_aspect_for_bytes_bytearray:
  <<: *default_aspect
  function_name: "iast_modulo_aspect_for_bytes_bytearray"
  default_function_type: "bytes"

modulo_aspect_for_bytearray_bytearray:
  <<: *default_aspect
  function_name: "iast_modulo_aspect_for_bytearray_bytearray"
  default_function_type: "bytearray"

modulo_noaspect:
  <<: *default_aspect
  function_name: "modulo_noaspect"
  iast_enabled: false

replace_aspect:
  <<: *default_aspect
  function_name: "iast_replace_aspect"

replace_noaspect:
  <<: *default_aspect
  function_name: "replace_noaspect"
  iast_enabled: false

repr_aspect:
  <<: *default_aspect
  function_name: "iast_repr_aspect"

repr_noaspect:
  <<: *default_aspect
  function_name: "repr_noaspect"
  iast_enabled: false

slice_aspect:
  <<: *default_aspect
  function_name: "iast_slice_aspect"

slice_noaspect:
  <<: *default_aspect
  function_name: "slice_noaspect"
  iast_enabled: false

stringio_aspect:
  <<: *default_aspect
  function_name: "iast_stringio_aspect"

stringio_noaspect:
  <<: *default_aspect
  function_name: "stringio_noaspect"
  iast_enabled: false

swapcase_aspect:
  <<: *default_aspect
  function_name: "iast_swapcase_aspect"

swapcase_noaspect:
  <<: *default_aspect
  function_name: "swapcase_noaspect"
  iast_enabled: false

title_aspect:
  <<: *default_aspect
  function_name: "iast_title_aspect"

title_noaspect:
  <<: *default_aspect
  function_name: "title_noaspect"
  iast_enabled: false

translate_aspect:
  <<: *default_aspect
  function_name: "iast_translate_aspect"

translate_noaspect:
  <<: *default_aspect
  function_name: "translate_noaspect"
  iast_enabled: false

upper_aspect:
  <<: *default_aspect
  function_name: "iast_upper_aspect"

upper_noaspect:
  <<: *default_aspect
  function_name: "upper_noaspect"
  iast_enabled: false
