add_aspect: &add_aspect
  warmups: 1
  function_name: "iast_add_aspect"
  iast_enabled: true

add_noaspect:
  <<: *add_aspect
  function_name: "add_noaspect"
  iast_enabled: false

add_inplace_aspect: &add_inplace_aspect
  warmups: 1
  function_name: "iast_add_inplace_aspect"
  iast_enabled: true

add_inplace_noaspect:
  <<: *add_inplace_aspect
  function_name: "add_inplace_noaspect"
  iast_enabled: false

bytearray_aspect: &bytearray_aspect
  warmups: 1
  function_name: "iast_bytearray_aspect"
  iast_enabled: true

bytearray_noaspect:
  <<: *bytearray_aspect
  function_name: "bytearray_noaspect"
  iast_enabled: false

bytearray_extend_aspect: &bytearray_extend_aspect
  warmups: 1
  function_name: "iast_bytearray_extend_aspect"
  iast_enabled: true

bytearray_extend_noaspect:
  <<: *bytearray_extend_aspect
  function_name: "bytearray_extend_noaspect"
  iast_enabled: false

bytes_aspect: &bytes_aspect
  warmups: 1
  function_name: "iast_bytes_aspect"
  iast_enabled: true

bytes_noaspect:
  <<: *bytes_aspect
  function_name: "bytes_noaspect"
  iast_enabled: false

bytesio_aspect: &bytesio_aspect
  warmups: 1
  function_name: "iast_bytesio_aspect"
  iast_enabled: true

bytesio_noaspect:
  <<: *bytesio_aspect
  function_name: "bytesio_noaspect"
  iast_enabled: false

capitalize_aspect: &capitalize_aspect
  warmups: 1
  function_name: "iast_capitalize_aspect"
  iast_enabled: true

capitalize_noaspect:
  <<: *capitalize_aspect
  function_name: "capitalize_noaspect"
  iast_enabled: false

casefold_aspect: &casefold_aspect
  warmups: 1
  function_name: "iast_casefold_aspect"
  iast_enabled: true

casefold_noaspect:
  <<: *casefold_aspect
  function_name: "casefold_noaspect"
  iast_enabled: false

decode_aspect: &decode_aspect
  warmups: 1
  function_name: "iast_decode_aspect"
  iast_enabled: true

decode_noaspect:
  <<: *decode_aspect
  function_name: "decode_noaspect"
  iast_enabled: false

encode_aspect: &encode_aspect
  warmups: 1
  function_name: "iast_encode_aspect"
  iast_enabled: true

encode_noaspect:
  <<: *encode_aspect
  function_name: "encode_noaspect"
  iast_enabled: false

format_aspect: &format_aspect
  warmups: 1
  function_name: "iast_format_aspect"
  iast_enabled: true

format_noaspect:
  <<: *format_aspect
  function_name: "format_noaspect"
  iast_enabled: false

format_map_aspect: &format_map_aspect
  warmups: 1
  function_name: "iast_format_map_aspect"
  iast_enabled: true

format_map_noaspect:
  <<: *format_map_aspect
  function_name: "format_map_noaspect"
  iast_enabled: false

index_aspect: &index_aspect
  warmups: 1
  function_name: "iast_index_aspect"
  iast_enabled: true

index_noaspect:
  <<: *index_aspect
  function_name: "index_noaspect"
  iast_enabled: false

join_aspect: &join_aspect
  warmups: 1
  function_name: "iast_join_aspect"
  iast_enabled: true

join_noaspect:
  <<: *join_aspect
  function_name: "join_noaspect"
  iast_enabled: false

strip_aspect: &strip_aspect
  warmups: 1
  function_name: "iast_strip_aspect"
  iast_enabled: true

strip_noaspect:
  <<: *strip_aspect
  function_name: "strip_noaspect"
  iast_enabled: false

rstrip_aspect: &rstrip_aspect
  warmups: 1
  function_name: "iast_rstrip_aspect"
  iast_enabled: true

rstrip_noaspect:
  <<: *rstrip_aspect
  function_name: "rstrip_noaspect"
  iast_enabled: false

lstrip_aspect: &lstrip_aspect
  warmups: 1
  function_name: "iast_lstrip_aspect"
  iast_enabled: true

lstrip_noaspect:
  <<: *lstrip_aspect
  function_name: "lstrip_noaspect"
  iast_enabled: false

lower_aspect: &lower_aspect
  warmups: 1
  function_name: "iast_lower_aspect"
  iast_enabled: true

lower_noaspect:
  <<: *lower_aspect
  function_name: "lower_noaspect"
  iast_enabled: false

ljust_aspect: &ljust_aspect
  warmups: 1
  function_name: "iast_ljust_aspect"
  iast_enabled: true

ljust_noaspect:
  <<: *ljust_aspect
  function_name: "ljust_noaspect"
  iast_enabled: false

modulo_aspect: &modulo_aspect
  warmups: 1
  function_name: "iast_modulo_aspect"
  iast_enabled: true

modulo_aspect_for_bytes:
  <<: *modulo_aspect
  function_name: "iast_modulo_aspect_for_bytes"
  iast_enabled: true

modulo_aspect_for_bytes_bytearray:
  <<: *modulo_aspect
  function_name: "iast_modulo_aspect_for_bytes_bytearray"
  iast_enabled: true

modulo_aspect_for_bytearray_bytearray:
  <<: *modulo_aspect
  function_name: "iast_modulo_aspect_for_bytearray_bytearray"
  iast_enabled: true

modulo_noaspect:
  <<: *modulo_aspect
  function_name: "modulo_noaspect"
  iast_enabled: false

replace_aspect: &replace_aspect
  warmups: 1
  function_name: "iast_replace_aspect"
  iast_enabled: true

replace_noaspect:
  <<: *replace_aspect
  function_name: "replace_noaspect"
  iast_enabled: false

repr_aspect: &repr_aspect
  warmups: 1
  function_name: "iast_repr_aspect"
  iast_enabled: true

repr_noaspect:
  <<: *repr_aspect
  function_name: "repr_noaspect"
  iast_enabled: false

slice_aspect: &slice_aspect
  warmups: 1
  function_name: "iast_slice_aspect"
  iast_enabled: true

slice_noaspect:
  <<: *slice_aspect
  function_name: "slice_noaspect"
  iast_enabled: false

stringio_aspect: &stringio_aspect
  warmups: 1
  function_name: "iast_stringio_aspect"
  iast_enabled: true

stringio_noaspect:
  <<: *stringio_aspect
  function_name: "stringio_noaspect"
  iast_enabled: false

swapcase_aspect: &swapcase_aspect
  warmups: 1
  function_name: "iast_swapcase_aspect"
  iast_enabled: true

swapcase_noaspect:
  <<: *swapcase_aspect
  function_name: "swapcase_noaspect"
  iast_enabled: false

title_aspect: &title_aspect
  warmups: 1
  function_name: "iast_title_aspect"
  iast_enabled: true

title_noaspect:
  <<: *title_aspect
  function_name: "title_noaspect"
  iast_enabled: false

translate_aspect: &translate_aspect
  warmups: 1
  function_name: "iast_translate_aspect"
  iast_enabled: true

translate_noaspect:
  <<: *translate_aspect
  function_name: "translate_noaspect"
  iast_enabled: false

upper_aspect: &upper_aspect
  warmups: 1
  function_name: "iast_upper_aspect"
  iast_enabled: true

upper_noaspect:
  <<: *upper_aspect
  function_name: "upper_noaspect"
  iast_enabled: false