name: "Rust CI"
on:
  push:
  pull_request:
    paths:
      - src/**

jobs:
  check:
    name: Rust CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension: ["src/native"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install latest stable toolchain and rustfmt
        run: rustup update stable && rustup default stable && rustup component add rustfmt clippy
      - name: Run cargo build
        run: cargo build --release
        working-directory: ${{ matrix.extension }}
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        working-directory: ${{ matrix.extension }}
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
        working-directory: ${{ matrix.extension }}
      - name: Run cargo test
        run: cargo test --no-fail-fast --locked
        working-directory: ${{ matrix.extension }}
